### ISSUE TITLE
Flower group rendering has overlapping flowers on 8th, 21th, 40th, etc flower

### ISSUE THREAD

**Issue by chendeni** [SMGCommunity/Whitehole-Neo#65]
The flowers from the flower group renderer overlap on the 8th, 21th, 40th, and so on because each circle of flower besides the center one has one too many flowers.  A new circle of flowers should begin after the 1st, 7th, 19th, 37th flower and so on.  
This means, the nth circle of flowers should have at most 1 flower if n=0, and 6n flowers for n>=1.  
Also, can you add a limit to the max number of flowers rendered so Whitehole doesn't crash when accidentally setting flower count 1 million?

**Comment by SuperHackio** [comment]
The overlapping plants is intentional, and not a bug. This is an oversight made by Nintendo, and Whitehole's renderer reflects that for accuracy.

A limit of 481 flowers (13 rings) has been added.
